apiVersion: apps/v1
kind: Deployment
metadata:
  name: image-classifier
spec:
  replicas: 1
  selector:
    matchLabels:
      app: classifier
  template:
    metadata:
      labels:
        app: classifier
    spec:
      containers:
        - name: api
          image: mlops-image-classifier:latest
          ports:
            - containerPort: 5000

